---
all:
  children:
    web_servers:
      hosts:
        hetzner1.hntoplinks.com
    app_servers:
      hosts:
        hetzner1.hntoplinks.com
    db_servers:
      hosts:
        hetzner1.hntoplinks.com
    prod:
      hosts:
        hetzner1.hntoplinks.com



